demos: ST: Fix typo in documentation
OpenAMP/openamp-docs pull request #34
Opened 2024-06-27 16:30 UTC by arnopo

Fix typo in some comments.

2024-07-26 05:34 UTC, edmooring requested changes

2024-07-26 05:34 UTC, edmooring commented on demos/system_reference-ST.rst
> +   # Umount potential media mounted from the sdcard. Replace <device> by mmcblk<X> (X = 0,1..) or
"Umount" or "Unmount"? Since the actual command is "eject", I think "Unmount" is more accurate.

2024-07-26 05:34 UTC, edmooring commented on demos/system_reference-ST.rst
> +   # Flash wic image on your sdcar. Replace <device> by mmcblk<X> (X = 0,1..) or
Additional typo fix: "sdcar" -> "sdcard".

2024-10-17 14:24 UTC, arnopo commented
@edmooring @tnmysh : can I merge this one?

2024-10-17 14:52 UTC, tnmysh approved these changes
LGTM.

2024-10-18 06:57 UTC, merged